web:
  build: .
  ports:
    - "80:80"
  links:
    - mysql
  env_file:
    - env
mysql:
  image: mysql:5.6.23
  env_file:
    - env
  volumes:
    - ./db:/var/lib/mysql:rw
    - ./bin/:/stack/bin:rw
  command: "/stack/bin/localdb-run.sh"